#!/usr/bin/env Rscript

source(file.path("R", "00_packages.R"))
load_required_packages(c("data.table", "glmnet", "ranger", "nnet", "knitr"))

run_script <- function(path) {
  message("Running ", path)
  source(path, local = new.env(parent = globalenv()))
}

# The main 120-month forecast panel already includes equal-weight and stacked
# combinations generated by R/05_run_rolling_forecasts.R. The scripts below
# rebuild the extended combination diagnostics used for supporting tables.
combination_scripts <- c(
  file.path("R", "paper", "result_scripts", "run_combo_equal_weight_ml_h_o_m_log_rolling.R"),
  file.path("R", "paper", "result_scripts", "run_equal_weight_clean_ml_combos_log_rolling.R"),
  file.path("R", "paper", "result_scripts", "run_ml_meta_combo_log_rolling.R"),
  file.path("R", "paper", "result_scripts", "run_combo_leaderboard_overview.R")
)

for (script in combination_scripts[file.exists(combination_scripts)]) {
  run_script(script)
}

message("Forecast-combination scripts complete.")
